# Generated by Django 5.0.3 on 2024-04-15 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cc_expiry_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cc_number',
            field=models.CharField(max_length=19, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(19), django.core.validators.RegexValidator(message='Credit number must be between 12 and 19 digits long', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvc',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3), django.core.validators.RegexValidator(message='Cvc must be 3 digits long', regex='^\\d{3}$')]),
        ),
    ]
