# Generated by Django 4.2.11 on 2024-04-05 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universitymember",
            name="phone_no",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    django.core.validators.MaxLengthValidator(10),
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="universitymember",
            name="ucid",
            field=models.CharField(
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.MaxLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="UCID must be exactly 8 digits.", regex="^\\d{8}$"
                    ),
                ],
            ),
        ),
    ]
