# Generated by Django 5.0.3 on 2024-04-17 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingspace_occupied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='reservation',
            name='stall',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingspace'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='lot_no',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
